Robot:
  Moter:
    circumference:
      - 55.0
  
    volt:
      - 0.0

  Lidar:
    threshold:
      - 3.5
  
  Gps:
    waypoint:
      - "./waypoint.csv" #Excelで編集厳禁

  Key_mode:
    speed:
      - 0x1FBBFFFF # W
      - 0x1F48FFFF # A
      - 0x1F33FFFF # S
      - 0x1F84FFFF # D

  Display_mode:
    order:
      - "./order.csv" #Excelで編集厳禁

  #未実装↓
  Order:
    speedx:
    # max 1.4
      - 1.0
    speed:
      -
      -
      -
      -
