[workspace]

members = [
    "core",
    "load-shdlib",
    "slam",
    "gps",
    "api",
    "lidar",
    "flacon",
    "robot-gpio",
    "robot-serialport",
    "rthred",
    "scheduler",
    "mytools",
    "camera",
]
