Robot:
  Moter:
    circumference:
      - 55.0
  
    volt:
      - 0.0

    right_gpio:
      - 23
      - 22

    left_gpio:
     - 21
     - 20

  Lidar:
    threshold:
      - 3.5

    Serial:
      port:
        - "/dev/ttyUSB0"
      rate:
        - 115200

  
  GPS:
    Serial:
      port:
        - "COM4"
      rate:
        - 115200
      buf_size:
        - 500
      
    waypoint:
      - "./waypoint.csv" #Excelで編集厳禁

  Key_mode:
    speed:
      - 0x1F55FFFF # W
      - 0x1F5CFFFF # A
      - 0x1FCCFFFF # S 
      - 0x1FC5FFFF # D

  Display_mode:
    order:
      - "./order.csv"
  RasPico:
    Serial:
      port:
        - "COM7"
      rate:
        - 9600

  #未実装↓
  Order:
    speedx:
    # max 1.4
      - 1.0
    speed:
      -
      -
      -
      -
