Robot:
  Moter:
    circumference:
      - 55.0
  
    volt:
      - 0.0

    right_gpio:
      - 25
      - 24

    left_gpio:
     - 23
     - 22

  Lidar:
    threshold:
      - 3.5

    Serial:
      port:
        - "COM4"

  
  GPS:
    Serial:
      port:
        - "COM4"
      rate:
        - 500
      buf_size:
        - 115200
      
    waypoint:
      - "./waypoint.csv" #Excelで編集厳禁

  Key_mode:
    speed:
      - 0x1FBBFFFF # W
      - 0x1F48FFFF # A
      - 0x1F33FFFF # S
      - 0x1F84FFFF # D

  Test_mode:
    - "./move.txt"

  Display_mode:
    order:
      - "./order.csv" #Excelで編集厳禁

  #未実装↓
  Order:
    speedx:
    # max 1.4
      - 1.0
    speed:
      -
      -
      -
      -
