[package]
name = "lidar_plot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotters = "0.3.1"
rand = "0.8.3"
rand_distr = "0.4.0"
rand_xorshift = "0.3.0"